#!/usr/bin/env bash
set -eo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export DRL_MULTI_TRAIN_FILE_NAME="${DRL_MULTI_TRAIN_FILE_NAME:-TD3_multi_dense5_bridge_geo_critic_from_5d}"
export DRL_MULTI_LOAD_MODEL_NAME="${DRL_MULTI_LOAD_MODEL_NAME:-TD3_velodyne_multi_v4_curriculum_stage2_to_5d_geo_critic_from_5a_guarded_best}"
export DRL_MULTI_LOAD_ACTOR_ONLY="${DRL_MULTI_LOAD_ACTOR_ONLY:-1}"
export DRL_MULTI_RESUME_TRAINING="${DRL_MULTI_RESUME_TRAINING:-0}"

export DRL_MULTI_USE_LOCAL_CRITIC=1
export DRL_MULTI_LOCAL_CRITIC_GEOMETRY_ONLY=1
export DRL_MULTI_LOCAL_CRITIC_MAX_AGENTS="${DRL_MULTI_LOCAL_CRITIC_MAX_AGENTS:-10}"
export DRL_MULTI_ACTIVE_NEIGHBORS_ONLY=1

export DRL_MULTI_REWARD_MODE=average
export DRL_MULTI_REWARD_SELF_WEIGHT="${DRL_MULTI_REWARD_SELF_WEIGHT:-0.8}"
export DRL_MULTI_USE_DISTANCE_WEIGHTED_REWARD=1
export DRL_MULTI_USE_LOCAL_NAVIGATION_REWARD=0

export DRL_MULTI_ACTOR_TRAIN_MODE="${DRL_MULTI_ACTOR_TRAIN_MODE:-full}"
export DRL_MULTI_ALLOW_FULL_ACTOR_FINETUNE=1
export DRL_MULTI_MAX_EPOCHS="${DRL_MULTI_MAX_EPOCHS:-6}"
export DRL_MULTI_EVAL_EPISODES="${DRL_MULTI_EVAL_EPISODES:-40}"
export DRL_MULTI_EXPL_NOISE="${DRL_MULTI_EXPL_NOISE:-0.025}"
export DRL_MULTI_EXPL_MIN="${DRL_MULTI_EXPL_MIN:-0.012}"
export DRL_MULTI_ACTOR_LR="${DRL_MULTI_ACTOR_LR:-0.000001}"
export DRL_MULTI_CRITIC_LR="${DRL_MULTI_CRITIC_LR:-0.00008}"
export DRL_MULTI_ACTOR_UPDATE_DELAY_STEPS="${DRL_MULTI_ACTOR_UPDATE_DELAY_STEPS:-20000}"
export DRL_MULTI_POLICY_FREQ="${DRL_MULTI_POLICY_FREQ:-2}"
export DRL_MULTI_ACTOR_ANCHOR_WEIGHT="${DRL_MULTI_ACTOR_ANCHOR_WEIGHT:-0.02}"
export DRL_MULTI_TRAINING_VERSION="${DRL_MULTI_TRAINING_VERSION:-dense5-bridge-geo-critic-from-5d-v1}"

exec "$PROJECT_ROOT/scripts/start_training_detached_multi_curriculum.sh" stage4_asym_dense_5_bridge
