#!/usr/bin/env bash
set -eo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export DRL_MULTI_TRAIN_FILE_NAME="${DRL_MULTI_TRAIN_FILE_NAME:-TD3_multi_dense5_bridge_from_5d_head_only}"
export DRL_MULTI_LOAD_MODEL_NAME="${DRL_MULTI_LOAD_MODEL_NAME:-TD3_velodyne_multi_v4_curriculum_stage2_to_5d_geo_critic_from_5a_guarded_best}"
export DRL_MULTI_LOAD_ACTOR_ONLY="${DRL_MULTI_LOAD_ACTOR_ONLY:-1}"
export DRL_MULTI_ACTOR_TRAIN_MODE="${DRL_MULTI_ACTOR_TRAIN_MODE:-head_only}"
export DRL_MULTI_RESUME_TRAINING="${DRL_MULTI_RESUME_TRAINING:-0}"

export DRL_MULTI_MAX_EPOCHS="${DRL_MULTI_MAX_EPOCHS:-8}"
export DRL_MULTI_EVAL_EPISODES="${DRL_MULTI_EVAL_EPISODES:-40}"
export DRL_MULTI_EXPL_NOISE="${DRL_MULTI_EXPL_NOISE:-0.018}"
export DRL_MULTI_EXPL_MIN="${DRL_MULTI_EXPL_MIN:-0.006}"
export DRL_MULTI_ACTOR_LR="${DRL_MULTI_ACTOR_LR:-0.0000005}"
export DRL_MULTI_CRITIC_LR="${DRL_MULTI_CRITIC_LR:-0.000025}"
export DRL_MULTI_ACTOR_UPDATE_DELAY_STEPS="${DRL_MULTI_ACTOR_UPDATE_DELAY_STEPS:-12000}"
export DRL_MULTI_POLICY_FREQ="${DRL_MULTI_POLICY_FREQ:-4}"
export DRL_MULTI_ACTOR_ANCHOR_WEIGHT="${DRL_MULTI_ACTOR_ANCHOR_WEIGHT:-0.05}"

exec "$PROJECT_ROOT/scripts/start_training_detached_multi_curriculum.sh" stage4_asym_dense_5_bridge
