#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

export DRL_ATTENTION_MODEL_NAME="${DRL_ATTENTION_MODEL_NAME:-TD3_velodyne_multi_v5_attention_bridge_residual_from_5d_conservative}"
export DRL_MULTI_CURRICULUM_CASES="${DRL_MULTI_CURRICULUM_CASES:-$PROJECT_ROOT/experiments/02_课程学习/cases/stage4_attention_bridge_residual_5_cases.json}"
export DRL_MULTI_CURRICULUM_SAMPLING="${DRL_MULTI_CURRICULUM_SAMPLING:-random}"
export DRL_ATTENTION_REPLAY_GROUP_RATIOS="${DRL_ATTENTION_REPLAY_GROUP_RATIOS:-standard:1.0,bridge:2.0}"
export DRL_ATTENTION_STANDARD_EVAL_GROUP="${DRL_ATTENTION_STANDARD_EVAL_GROUP:-standard}"
export DRL_ATTENTION_DENSE_EVAL_GROUPS="${DRL_ATTENTION_DENSE_EVAL_GROUPS:-bridge}"
export DRL_ATTENTION_MAX_RESIDUAL="${DRL_ATTENTION_MAX_RESIDUAL:-0.12}"
export DRL_ATTENTION_ACTOR_LR="${DRL_ATTENTION_ACTOR_LR:-0.000002}"
export DRL_ATTENTION_CRITIC_LR="${DRL_ATTENTION_CRITIC_LR:-0.00002}"
export DRL_ATTENTION_ACTOR_START_STEP="${DRL_ATTENTION_ACTOR_START_STEP:-8000}"
export DRL_ATTENTION_ACTOR_WARMUP_STEPS="${DRL_ATTENTION_ACTOR_WARMUP_STEPS:-15000}"
export DRL_ATTENTION_REWARD_SCALE="${DRL_ATTENTION_REWARD_SCALE:-0.05}"
export DRL_ATTENTION_GATE_PENALTY="${DRL_ATTENTION_GATE_PENALTY:-0.3}"
export DRL_ATTENTION_RESIDUAL_PENALTY="${DRL_ATTENTION_RESIDUAL_PENALTY:-0.2}"
export DRL_ATTENTION_STANDARD_RESIDUAL_PENALTY="${DRL_ATTENTION_STANDARD_RESIDUAL_PENALTY:-2.0}"
export DRL_ATTENTION_EXPLORATION_NOISE="${DRL_ATTENTION_EXPLORATION_NOISE:-0.006}"
export DRL_ATTENTION_LEARNING_STARTS="${DRL_ATTENTION_LEARNING_STARTS:-2500}"
export DRL_ATTENTION_EVAL_INTERVAL="${DRL_ATTENTION_EVAL_INTERVAL:-20}"
export DRL_ATTENTION_MAX_EPISODES="${DRL_ATTENTION_MAX_EPISODES:-400}"
export DRL_ATTENTION_EARLY_STOPPING_PATIENCE="${DRL_ATTENTION_EARLY_STOPPING_PATIENCE:-6}"

exec "$PROJECT_ROOT/scripts/start_training_detached_spatiotemporal_attention_5d.sh"
