#!/usr/bin/env bash
set -eo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export DRL_MULTI_TRAIN_FILE_NAME="${DRL_MULTI_TRAIN_FILE_NAME:-TD3_multi_dense5_moderate_residual_from_5d}"
export DRL_MULTI_LOAD_MODEL_NAME="${DRL_MULTI_LOAD_MODEL_NAME:-TD3_velodyne_multi_v4_curriculum_stage2_to_5d_geo_critic_from_5a_guarded_best}"
export DRL_MULTI_LOAD_ACTOR_ONLY=1
export DRL_MULTI_ACTOR_TRAIN_MODE=residual
export DRL_MULTI_RESIDUAL_HIDDEN_DIM="${DRL_MULTI_RESIDUAL_HIDDEN_DIM:-128}"
export DRL_MULTI_RESIDUAL_SCALE="${DRL_MULTI_RESIDUAL_SCALE:-0.15}"
export DRL_MULTI_RESUME_TRAINING="${DRL_MULTI_RESUME_TRAINING:-0}"

export DRL_MULTI_USE_LOCAL_CRITIC=1
export DRL_MULTI_LOCAL_CRITIC_GEOMETRY_ONLY=1
export DRL_MULTI_LOCAL_CRITIC_MAX_AGENTS="${DRL_MULTI_LOCAL_CRITIC_MAX_AGENTS:-10}"
export DRL_MULTI_ACTIVE_NEIGHBORS_ONLY=1

export DRL_MULTI_USE_DYNAMIC_REWARD=0
export DRL_MULTI_REWARD_MODE=average
export DRL_MULTI_USE_DISTANCE_WEIGHTED_REWARD=0
export DRL_MULTI_USE_LOCAL_NAVIGATION_REWARD=0

export DRL_MULTI_MAX_EPOCHS="${DRL_MULTI_MAX_EPOCHS:-8}"
export DRL_MULTI_EVAL_EPISODES="${DRL_MULTI_EVAL_EPISODES:-40}"
export DRL_MULTI_EXPL_NOISE="${DRL_MULTI_EXPL_NOISE:-0.020}"
export DRL_MULTI_EXPL_MIN="${DRL_MULTI_EXPL_MIN:-0.008}"
export DRL_MULTI_ACTOR_LR="${DRL_MULTI_ACTOR_LR:-0.0001}"
export DRL_MULTI_CRITIC_LR="${DRL_MULTI_CRITIC_LR:-0.00006}"
export DRL_MULTI_ACTOR_UPDATE_DELAY_STEPS="${DRL_MULTI_ACTOR_UPDATE_DELAY_STEPS:-5000}"
export DRL_MULTI_POLICY_FREQ="${DRL_MULTI_POLICY_FREQ:-2}"
export DRL_MULTI_ACTOR_ANCHOR_WEIGHT="${DRL_MULTI_ACTOR_ANCHOR_WEIGHT:-0.02}"
export DRL_MULTI_TRAINING_VERSION="${DRL_MULTI_TRAINING_VERSION:-dense5-moderate-residual-from-5d-v1}"

exec "$PROJECT_ROOT/scripts/start_training_detached_multi_curriculum.sh" stage4_asym_dense_5_moderate
